# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: gen-testapi
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
